import { DollarSign, PiggyBank, ShoppingCart, Home, Briefcase, Heart, Utensils, BookOpen, Tv, Gift, User, LineChart, Banknote, Medal, GraduationCap, Ellipsis, Coins } from "lucide-react";

export const Colors = [
  {
    value: "amount",
    name: "Amount",
    colorName: "Coral",
    color: "hsl(var(--chart-1))",
    icon: <Coins />,
  },
  {
    value: "rent",
    name: "Rent",
    colorName: "Teal",
    color: "hsl(var(--chart-2))",
    icon: <Home />,
  },
  {
    value: "groceries",
    name: "Groceries",
    colorName: "Deep Blue",
    color: "hsl(var(--chart-3))",
    icon: <ShoppingCart />,
  },
  {
    value: "transportation",
    name: "Transportation",
    colorName: "Goldenrod",
    color: "hsl(var(--chart-4))",
    icon: <Briefcase />,
  },
  {
    value: "entertainment",
    name: "Entertainment",
    colorName: "Amber",
    color: "hsl(var(--chart-5))",
    icon: <Tv />,
  },
  {
    value: "utilities",
    name: "Utilities",
    colorName: "Purple",
    color: "hsl(var(--chart-6))",
    icon: <DollarSign />,
  },
  {
    value: "healthcare",
    name: "Healthcare",
    colorName: "Pink",
    color: "hsl(var(--chart-7))",
    icon: <Heart />,
  },
  {
    value: "dining",
    name: "Dining Out",
    colorName: "Sky Blue",
    color: "hsl(var(--chart-8))",
    icon: <Utensils />,
  },
  {
    value: "subscriptions",
    name: "Subscriptions",
    colorName: "Lime Green",
    color: "hsl(var(--chart-9))",
    icon: <BookOpen />,
  },
  {
    value: "savings",
    name: "Savings",
    colorName: "Lavender",
    color: "hsl(var(--chart-10))",
    icon: <PiggyBank />,
  },
  {
    value: "misc",
    name: "Miscellaneous",
    colorName: "Bright Blue",
    color: "hsl(var(--chart-11))",
    icon: <Ellipsis />,
  },
  {
    value: "salary",
    name: "Salary",
    colorName: "Violet",
    color: "hsl(var(--chart-12))",
    icon: <User />,
  },
  {
    value: "freelance",
    name: "Freelance",
    colorName: "Green",
    color: "hsl(var(--chart-13))",
    icon: <LineChart />,
  },
  {
    value: "investments",
    name: "Investments",
    colorName: "Orange",
    color: "hsl(var(--chart-14))",
    icon: <Banknote />,
  },
  {
    value: "bonus",
    name: "Bonuses",
    colorName: "Orchid",
    color: "hsl(var(--chart-15))",
    icon: <Medal />,
  },
  {
    value: "scholarship",
    name: "Scholarships",
    colorName: "Yellow",
    color: "hsl(var(--chart-16))",
    icon: <GraduationCap />,
  },
  {
    value: "rentalIncome",
    name: "Rental Income",
    colorName: "Red",
    color: "hsl(var(--chart-17))",
    icon: <Home />,
  },
  {
    value: "sideBusiness",
    name: "Side Business",
    colorName: "Magenta",
    color: "hsl(var(--chart-18))",
    icon: <Briefcase />,
  },
  {
    value: "royalties",
    name: "Royalties",
    colorName: "Cerulean",
    color: "hsl(var(--chart-19))",
    icon: <Tv />,
  },
  {
    value: "cashGifts",
    name: "Cash Gifts",
    colorName: "Golden Yellow",
    color: "hsl(var(--chart-20))",
    icon: <Gift />,
  }
];
